#!/usr/bin/env python3
"""Pin the NIH 3D/PDB 1K3V capsid as the Virus Length model."""

import argparse
import json
import urllib.request
from pathlib import Path

from fetch_model_assets import check_matches, inspect_glb, sha, write_json


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "content/visualizations/models.json"
OUTPUT = ROOT / "content/visualizations/models/nih-porcine-parvovirus-capsid.glb"
DOWNLOAD = "https://3d.nih.gov/api/submissions/11748/runs/5857566f-fc26-4534-8b11-48897c408ea3/output-files/261470"
SOURCE_SHA256 = "69cf2b1a3704326b0cf5b2ae8a969a4da34d8ef79b9f0d7aa9c15b4339a74515"


def import_model(source_file=None):
    if source_file:
        data = Path(source_file).read_bytes()
    else:
        with urllib.request.urlopen(DOWNLOAD, timeout=30) as response:
            data = response.read(2_000_001)
    if len(data) > 2_000_000 or sha(data) != SOURCE_SHA256:
        raise ValueError("NIH capsid source changed or exceeds the 2 MB asset budget")
    registry = json.loads(REGISTRY.read_text())
    entry = {
        "id": "nih-porcine-parvovirus-capsid",
        "source": "https://3d.nih.gov/entries/9728",
        "author": "NIH 3D; structural model from PDB 1K3V",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "license_files": ["licenses/CC-BY-4.0.txt"],
        "matches": {"length": ["Virus"]},
        "geometry": "mesh",
        "note": "Molecular surface of the porcine parvovirus capsid from PDB 1K3V, "
                "generated by NIH 3D. The 28 nm marker is this capsid's approximate diameter, "
                "not a universal virus size. The model shows the protein shell, not the genome "
                "or a measured individual virion. Surface colors distinguish protein chains.",
        "src": str(OUTPUT.relative_to(ROOT)),
        "source_sha256": SOURCE_SHA256,
        "source_bytes": len(data),
        "processing": {"operations": ["Retain NIH 3D's embedded molecular surface and chain colors"],
                       "pdb_id": "1K3V", "nih_output_file_id": 261470,
                       "download_url": DOWNLOAD},
        "volume_semantics": "cubic_linear_equivalent_approximation",
        "closed_volume_checked": False,
        **inspect_glb(data),
    }
    replacement_ids = {"sketchfab-virus-capsid", entry["id"]}
    updated = [model for model in registry["models"] if model["id"] not in replacement_ids]
    updated.append(entry)
    check_matches(updated)
    OUTPUT.write_bytes(data)
    registry["models"] = updated
    write_json(REGISTRY, registry)
    print(f"Imported {OUTPUT.name}: {len(data):,} bytes")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-file", type=Path, help="Use a previously downloaded NIH GLB")
    import_model(parser.parse_args().source_file)
